### ISSUE TITLE
Etoffer le TL;DR

### ISSUE THREAD

**Issue by Vayel** [Vayel/Python-3.5#5]
Comme dit sur ZdS, il me semble judicieux d'étoffer la section _TL;DR_. Certes, il s'agit d'un résumé seulement, mais il est tellement court qu'on peut difficilement en tirer quelque chose. Le plus simple, court et efficace pour remédier à cela serait, je pense, de fournir un exemple de code pour chaque.

Notamment, la puce à propos de l'_unpacking_ m'apparaît complètement floue. Bien sûr, on va la détailler plus bas, mais cela n'illustre-t-il pas le fait que le résumé n'est pas assez explicite ?

**Comment by cgabard** [comment]
probablement

**Comment by cgabard** [comment]
Est ce que du coup avec la mise a jour c'est suffisant ?

Il faut éviter d'en mettre trop sinon ça ne sert plus son rôle de résumé rapide

**Comment by Vayel** [comment]
Mises à part mes quelques remarques, pour lesquelles je ferai des PR (sur ta branche), ça me va tout à fait.
