### ISSUE TITLE
Async et await : pré-requis

### ISSUE THREAD

**Issue by Vayel** [Vayel/Python-3.5#6]
Tout bien réfléchi, il ne me semble pas une bonne idée de ré-expliquer les bases de la programmation asynchrone, des coroutines et compagnie dans la section sur la PEP-492. Non seulement ça rallongera l'article, mais je doute qu'on puisse le faire correctement en si peu de place.

**Comment by cgabard** [comment]
Je pense qu'on peut reformuler un peu pour clarifier les chosesq mais effectivement beaucoup plus long ne sera pas possible

**Comment by Vayel** [comment]
Comme dit dans #12, je ne suis pas au point sur les coroutines. Mais si on se limite dans l'article à l'emploi dans le cas "programmation asynchrone de manière synchrone", on peut s'inspirer de [cela](http://hackedbellini.org/development/writing-asynchronous-python-code-with-twisted-using-inlinecallbacks/).

En gros, on aurait le raisonnement suivant : 
- Prog asynchrone de manière générale : callbacks
- En Python 3.4 : décorateur et yield
- En Python 3.5 : async et await

Le premier point ne serait qu'un rappel (la prog asynchrone serait un pré-requis).

**Comment by cgabard** [comment]
C'est ce que j'ai essayé de faire mais en phrase pour éviter une trop longue section.

**Comment by Vayel** [comment]
Je vais faire une PR pour l'introduction de cette section. Il sera plus simple de réagir à partir de là.

**Comment by cgabard** [comment]
Yep. De toute façon je pensais re-passer sur cette section une fois que le gros serait rédigé.

**Comment by cgabard** [comment]
Ça a été fait.
