### ISSUE TITLE
Suite

### ISSUE THREAD

**Issue by cgabard** [Vayel/Python-3.5#8]
@Vayel : Bon on a des premières versions de chaque partie. Il serait peut-être pas mal, après une passe de relecture, de tout merger et de transférer sur zds. Ça nous permetrait de voir où on en est.

Ensuite je serais pour faire des petites PR pour les modifs que l'autre relirai et qu'on merge tout au fur et à mesure. Parce que là c'est un peu dur de s'y retrouver.

Rappel : On a jusqu'au 13 semptembre (date de la sortie officiel) sachant qu'à partir du  je risque d'être difficilement joignable.

**Comment by Vayel** [comment]
Ouep. Je jette un coup d'oeil aux dernières versions puis merge ça (sauf si tu veux merger).

Fera-t-on une bêta ?

> Rappel : On a jusqu'au 13 semptembre (date de la sortie officiel) sachant qu'à partir du je risque d'être difficilement joignable.

Du ? :P 

Je rentre chez moi le 26 et aurai beaucoup de temps à consacrer à l'article à partir de cette date (jusqu'à la rentrée, le 7).

**Comment by cgabard** [comment]
du 11.

Fais les quelques modifs que tu veux sur les PR en cours, merge les et on verra où on en sera

**Comment by cgabard** [comment]
Bon en dehors des PR en cours, le prochain gros chantier va être "ce qui peu être attendu sur la 3.6". Je vais essayé de faire une première version rapidement pour qu'on est une première version de l'ensemble. 

Ensuite je ferais des grosses passes de relectures.

Si tu penses qu'il faille rajouter des sections on peut en parler mais l'article me semble déjà assez dense, non ?

**Comment by Vayel** [comment]
Je ne vois pas de sections à ajouter, en effet.

Par contre, je suis mitigé sur le fait de commencer la suite dès maintenant. Pour moi, il serait préférable d'atteindre une forme plus ou moins définitive au niveau de l'essentiel (la version 3.5) puis de nous pencher par la suite sur le plus optionnel. 

Il me semble donc judicieux de mettre rapidement le contenu en bêta et de demander l'avis des membres sur les parties optionnelles.

Il faudra aussi prévenir les validos par rapport à l'échéance.

**Comment by cgabard** [comment]
Comme tu le souhaite.

Je te propose qu'on travail sur le fond cette semaine et on verra. J'aurai peut etre du temps jeudi soir, j'en profiterai à ce moment là pour rédiger ce morceau (car il me faut quelques heures contigue pour ça). Après le gros sera prêt, on pourra envisager la beta. Et je demanderai à nohar de passer dessus.

Pour les validos, suffira de le demander au moment de la demande de validation, c'est pas grave ça. Au pire je m'arrangerai avec Arius

**Comment by cgabard** [comment]
Je suis perplexe sur la mise en beta. On risque de perdre "leffet de surprise" pour la sortie. Si quelques membres type nohar + valido peuvent passer dessus, ce n'est peut être pas necessaire.

**Comment by Vayel** [comment]
Oui, tu as raison. Mais du coup, il faut choisir des membres s'y connaissant en Python et ayant le temps de nous relire. artragis me semble un bon relecteur.

**Comment by cgabard** [comment]
Ou lustaf. Commençons par finir cette semaine une première version. Ça sert
à rien de ramener des lecteurs avant une version qui nous plaît

Christophe

**Comment by cgabard** [comment]
Bon j'ai fais une PR sur la version 3.6

Je vais essayer de repasser sur async et await dans le week-end, si tu as du temps, passe plutôt sur le reste et hésite pas à corriger mes PR et les merger.

**Comment by cgabard** [comment]
J'ai un ajout sur async de prêt que je pousserai des que je peux accéder à internet depuis mon PC.

Je vais voir si il y a assez d'infos pour faire une rapide section sur le support de Python 3.5 dans les outils annexes. Sinon je preparerai juste un commentaire à l'article que je mettrai le jour de ma sortie.

Une fois mes dernières parties poussés et mergé, on pourra se faire quelques relecture global et demander quelques avis extérieurs !

**Comment by Vayel** [comment]
Vu qu'il nous reste peu de choses à faire avant la version "finale", je propose de partir à la chasse aux relecteurs. Comment on s'organise ? On les ping ici ? On les ajoute en auteurs à l'article sur ZdS ?

**Comment by cgabard** [comment]
Lundi j'envoie un mp à quelqu'un avec une version propre sur zds et le
liens vers le dépôt pour l'édition. Ca te va ?

Christophe

**Comment by Vayel** [comment]
Ouep

**Comment by cgabard** [comment]
Je ferme les tickets pour préparer la version vers les auteurs externes

**Comment by Vayel** [comment]
Je passe juste pour dire que je n'ai pas accès à Internet ces temps-ci. Donc ne m'attends pas. ^^
