### ISSUE TITLE
Ordre

### ISSUE THREAD

**Issue by Vayel** [Vayel/Python-3.5#9]
L'ordre dans lequel les PEP sont abordées est-il volontaire ? Commencer par les coroutines, sujet compliqué, n'est peut-être pas souhaitable.

**Comment by cgabard** [comment]
Non pas spécialement de préférence, je les ai mit un peu au hasard (sauf l'unpacking qui est en dernier parce qu'il a été ajouté le dernier, apres que j'ai commencé l'article).

Bref ré-organise si tu veux.

**Comment by Vayel** [comment]
Je commencerais bien par l'unpacking : ça concerne tous les programmeurs Python et les ajouts permettent de faire des trucs très chouettes.

Vu que les annotations risquent de concerner peu de monde, je les placerais bien à la fin.

Pour les deux autres, je ne sais pas.

**Comment by cgabard** [comment]
Vas y hésite pas

**Comment by cgabard** [comment]
mergé
